export const SET_VIDEO_TITLE = 'SET_VIDEO_TITLE';
export const SET_SENTIMENT = 'SET_SENTIMENT';
export const SET_SENTIMENT_COUNT = 'SET_SENTIMENT_COUNT';
export const SET_HIGHEST_COMMENT = 'SET_HIGHEST_COMMENT';
export const SET_LOWEST_COMMENT = 'SET_LOWEST_COMMENT';
export const SET_KEYCOUNTS = 'SET_KEYCOUNTS';
export const SET_COMMENT_COUNT = 'SET_COMMENT_COUNT';
export const SET_COMMENTS = 'SET_COMMENTS';
export const SET_HIGHEST_AND_LOWEST_COMMENT_COUNT =
  'SET_HIGHEST_AND_LOWEST_COMMENT_COUNT';
export const SET_HIGHEST_SENTIMENT_SINGLE_WORDS =
  'SET_HIGHEST_SENTIMENT_SINGLE_WORD';
export const SET_LOWEST_SENTIMENT_SINGLE_WORDS =
  'SET_LOWEST_SENTIMENT_SINGLE_WORD';
export const SET_CHOICE = 'SET_CHOICE';
export const TOGGLE_NO_COMMENTS_MODAL = 'TOGGLE_NO_COMMENTS_MODAL';
